[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the Next.js plugin handle all routing
# [[redirects]]
#   from = "/page/*"
#   to = "/.netlify/functions/next"
#   status = 200 